---
version: 2
models:
- name: "latlog_test2__create_point_1_1"
  tags:
  - "prophecy_temp"
- name: "latlog_test2__create_point_gem_seed_2"
  tags:
  - "prophecy_temp"
- name: "latlog_test2__single_point_1"
  tags:
  - "prophecy_temp"
- name: "latlog_test2__single_point_1_1"
  tags:
  - "prophecy_temp"
- name: "latlog_test2__single_point_1_2"
  tags:
  - "prophecy_temp"
- name: "latlog_test2__single_point_1_3"
  tags:
  - "prophecy_temp"
