---
version: 2
models:
- name: "model_latlong3_single_point_1"
  tags:
  - "prophecy_temp"
- name: "model_latlong3_single_point_1_1"
  tags:
  - "prophecy_temp"
- name: "model_latlong3_single_point_1_2"
  tags:
  - "prophecy_temp"
- name: "model_latlong3_single_point_1_3"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__latlong3"
  database: "sony"
  schema: "orch_test"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mbrjvs6c__latlong3__dataLatLong_csv_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy_tmp__mbrjvs6c__latlong3__single_point_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy_tmp__mbrjvs6c__latlong3__single_point_1_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy_tmp__mbrjvs6c__latlong3__single_point_1_2"
    tags:
    - "prophecy_temp"
  - name: "prophecy_tmp__mbrjvs6c__latlong3__single_point_1_3"
    tags:
    - "prophecy_temp"
