---
version: 2
models:
- name: "latlog__charts"
  tags:
  - "prophecy_temp"
- name: "latlog__create_point"
  tags:
  - "prophecy_temp"
- name: "latlog__distance_comparison"
  tags:
  - "prophecy_temp"
- name: "latlog__points"
  tags:
  - "prophecy_temp"
- name: "latlog__single_point"
  tags:
  - "prophecy_temp"
