name: fsdsfdsfd
description: ''
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectautomationpr
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-08-05 08:47:39'
pipelines:
  pipelines/asdasd:
    name: asdasd
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-08-05 08:47:39'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-08-05 08:47:39'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-08-05T08:47:39.773245Z'
  name: plibMaven
  version: 8.11.1
  id: '1898656138'
  createdAt: '2025-08-05T08:47:39.773245Z'
  type: plibMaven
- modifiedAt: '2025-08-05T08:47:39.773245Z'
  name: plibPypi
  version: 2.0.11
  id: '732068322'
  createdAt: '2025-08-05T08:47:39.773245Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.47
    isDefault: true
    author: null
    createdAt: '2025-08-05 08:47:28'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-08-05 08:47:28'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
